name: Publish

on:
  push:
    branches: [main]

jobs:
  default_ci:
    name: Run default CI of repository
    uses: ./.github/workflows/ci.yml
    
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Init docker
        run: |
          docker compose -f docker-compose.yml up -d
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}