name: Test and Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Run default CI of repository
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}