name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm

  lint:
    name: Run lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Lint check
        run: pnpm lint

  type-check:
    name: Run type check
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Build
        run: pnpm run build
      - name: Init example Prisma
        run: pnpm -F example-prisma run generate
      - name: Init Prisma
        run: pnpm -F @gqloom/prisma run init
      - name: Type check
        run: pnpm run check:type

  test:
    name: Run Unint test
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: ./.github/actions/pnpm
      - name: Build
        run: pnpm run build
      - name: Init Prisma
        run: pnpm -F @gqloom/prisma run init
      - name: Test
        run: pnpm test
